### ISSUE TITLE
Org details

### ISSUE THREAD

**Issue by rashil2000** [ScoopInstaller/.github#2]
![image](https://user-images.githubusercontent.com/46838874/145156456-832d0a6a-6d01-40fa-b877-50a5df16199c.png)

![image](https://user-images.githubusercontent.com/46838874/145156310-aa86f5cf-72ca-48e8-9104-cd5eea5d9cd1.png)

I have some suggestions based on how Homebrew does it:
- Add description as "A command-line installer for Windows."
- Add location as GitHub
- Remove the trailing slash from URL
- We don't have an email ID or twitter account, we can leave that out for now
- Maybe add a Sponsor button?
- Remove the Readme.md file in profile, I think it's not adding any new info and looks out of place right now

/cc @rasa

**Comment by rasa** [comment]
> * Add description as "A command-line installer for Windows."

Done

> * Add location as GitHub

Can't figure out how. The only options I see are actual countries.

> * Remove the trailing slash from URL

Done.

> * We don't have an email ID or twitter account, we can leave that out for now

Ok. 

> * Maybe add a Sponsor button?

Ok. Luke is paying for the domain scoop.sh so it should go to him.

> * Remove the Readme.md file in profile, I think it's not adding any new info and looks out of place right now

Done.

**Comment by rasa** [comment]
Just an FYI, I was able to change the org's location to `GitHub` via
```
curl -H "Authorization: bearer github_token" -d '{"location":"GitHub"}' https://api.github.com/orgs/ScoopInstaller
```
The [Sponsor] icon displays for Homebrew, and they also have GitHub as their location, so it shouldn't matter what it's set to.

**Comment by rashil2000** [comment]
> Just an FYI, I was able to change the org's location to `GitHub` via
> 
> ```
> curl -H "Authorization: bearer github_token" -d '{"location":"GitHub"}' https://api.github.com/orgs/ScoopInstaller
> ```

Oh, interesting, how did you discover this 😅

**Comment by goyalyashpal** [comment]
> * Remove the trailing slash from URL

why this though? 🤔

**Comment by rasa** [comment]
> Oh, interesting, how did you discover this 😅

Google, I think. @rashil2000
